### ISSUE TITLE
Pokémon Crystal Clear v2.5.9 patch update request

### ISSUE THREAD

**Issue by Flauscheloni** [BestPig/analogue-pocket-patches#2]
Bonjour BestPig, I hope it's ok to ask here - would you be so kind as to look into making an update to your patch for Pokémon Crystal Clear, which is now in version 2.5.9 ? Between you and @JoseJX it seems you guys made the older versions work.
ShockSlayer made a lot of improvements in the time since your last patch (for 2.5.5) and now 2.5.9 two weeks ago that makes it worth updating. 
I tried my luck using the older patches, but to no avail, I only get a blank screen when trying to run it in GB Studio. Patching a clean Crystal v1.1 with its appropriate patch for GB Studio first and then apply the Crystal Clear 2.5.9 bps patch got it in a playable state at least, but I can already see graphical glitches with menus etc., so I assume that's what you already fixed with previous versions specifically made to patch CrystalClear. 
ShockSlayer keeps the patches on the Discord server https://discord.gg/tskaCr2 , 2_5_9_Standard_1_1.bps or 2_5_9_Standard_1_0.bps depending the base Crystal Version.
Thank you so much!

**Comment by JoseJX** [comment]
Please test it with the [Pokemon Patcher](https://josejx.net/PokePatcher/), it should "just work". If not, please let me know.

**Comment by Flauscheloni** [comment]
Thanks for your quick reply JoseJX! I didn't know this patcher existed or I would have tried it first. It seems like it's working well so far, the graphical glitches I encountered earlier are gone using your patcher. I Iguess I can close this, as anyone can just use your patcher and doesn't need a dedicated patch.
